#!/usr/bin/bash


run_latehook() {

   real_root=/real_root
   new_root=/new_root
   mkdir -p $real_root $new_root

	mnt=/mnt
	snapshot_dir=/.snapshots
	cd $mnt$snapshot_dir

	#echo mount -m LABEL=ROOT2 $mnt
	#echo mount --bind $mnt/@root /new_root


	echo -e "\nWhat would you like to do?\n
<s> boot into a snapshot
<b> enter bash
<r> recover snapshot\n"

	read -s -t 5 -n 1 key

	if [ $key = 's' ]; then
	
		echo -e "\nType the name of the snapshot you would like to load.\n"
		
		ls

		echo

		read snapshot
	
		if [ -d "$snapshot" ]; then

			umount $new_root
			mount --bind "$mnt$snapshot_dir/$snapshot" $new_root
			mount --bind "$mnt$snapshot_dir" "$new_root$snapshot_dir"
		else
			echo -e "\nThe snapshot \'snapshot\' does not exist!\n"
			bash
		fi

	elif [ $key = 'b' ]; then

		echo "Entering bash..."
		bash
		
		#umount $new_root
		#mount --bind $mnt/@root $mnt
	else
		bash
	fi
	

}
