#!/bin/sh

build() {
	add_binary rsync
	add_binary bash
	add_binary btrfs
	add_binary unsquashfs 
	add_binary mksquashfs
	add_module overlay
	add_module loop
	add_module squashfs
	add_module vfat
	add_runscript
}

help() {
	cat << HELPEOF
Run Arch as tmpfs, overlay, squashfs, or snapshot
HELPEOF
}
