#!/usr/bin/sh


create_archive() {
            
   echo "Creating archive file..."
   cd /real_root/@/

   tar --exclude=rootfs.tar.gz --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ --exclude=/mnt/ --exclude=/etc/pacman.d/gnupg/ -czf /real_root/@/rootfs.tar.gz . 
}


run_latehook() {

   echo -e "\nPress any key for extra boot options.\n"

   if read -t 4 -s -n 1; then


      echo -e "\nPlease choose an option:\n\n<o> run in overlay mode\n<e> extract archive to tmpfs\n<c> copy / directly to tmpfs\n<n> create a new archive file\n<d> enter emergency shell\n<b> continue boot\n"

      read -n 1 -s key


      if [[ "$key" = "o" ]]; then

         ROOT_MNT="/new_root"
         OFS_DIRS="/run/archroot"
         OFS_LOWER="${OFS_DIRS}/root_ro"
         OFS_COWSPACE="${OFS_DIRS}/cowspace"
         OFS_UPPER="${OFS_COWSPACE}/upper"
         OFS_WORK="${OFS_COWSPACE}/work"

         mkdir -p ${OFS_LOWER}
         mount --move ${ROOT_MNT} ${OFS_LOWER}

         mkdir -p ${OFS_COWSPACE}
         mount -t tmpfs cowspace ${OFS_COWSPACE}

         mkdir -p ${OFS_UPPER}
         mkdir -p ${OFS_WORK}

         mount -t overlay -o lowerdir=${OFS_LOWER},upperdir=${OFS_UPPER},workdir=${OFS_WORK} rootfs ${ROOT_MNT}


      elif [[ "$key" = "e" ]] || [[ "$key" = "n" ]] || [[ "$key" = "c" ]]; then

         poll_device ${root} 2
         mkdir /real_root/
         mount ${root} /real_root/
         mount -t tmpfs -o size=80% none /new_root/
      
         if [[ "$key" = "e" ]] || [[ "$key" = "n" ]]; then

            [[ ! -f "/real_root/@/rootfs.tar.gz" ]] || [[ "$key" = "n" ]] && create_archive

            echo "Extracting archive to RAM. Please be patient..."
            tar -xzf /real_root/@/rootfs.tar.gz -C /new_root/

         elif [[ "$key" = "c" ]]; then

            echo "Copying root filesystem to RAM. Please be patient..."

            #cp -p -a -R /real_root/@/* /new_root/
            rsync -a --exclude=rootfs.tar.gz --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ --exclude=/mnt/ /real_root/@/ /new_root/

         fi

         touch /new_root/LIVE
         umount /real_root/

         LIVE_mount() {
            echo "Live system on RAM."
         }
         
         mount_handler=LIVE_mount

      elif [[ "$key" = "d" ]]; then

         echo "Entering emergency shell."

         bash

      elif [[ "$key" = "b" ]]; then

         echo "Continuing boot..."

      fi

   fi
}


