#!/usr/bin/bash


create_archive() {
            
   echo "Creating archive file..."
   cd /real_root/@/

   tar --exclude=rootfs.tar.gz --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ --exclude=/mnt/ --exclude=/etc/pacman.d/gnupg/ -czf /real_root/@/rootfs.tar.gz . 
}


run_latehook() {

   echo -e "\nPress any key for extra boot options.\n"

   if read -t 4 -s -n 1; then


      echo -e "\nPlease choose an option:\n\n<s> snapshot mode\n<o> run in overlay mode 1\n<p> run in overlay mode 2\n<e> extract archive to tmpfs\n<c> copy / directly to tmpfs\n<n> create a new archive file\n<d> enter emergency shell\n<b> continue boot\n"

      read -n 1 -s key


      if [[ "$key" = "s" ]]; then

         echo "Premount" 
         poll_device ${root} 2

         root_dir=/new_root

         mkdir -p $root_dir 

         mount --mkdir -o subvolid=256 ${root} $root_dir
      
         btrfs subvolume list -ts $root_dir | less
         read -n 3 -p "Choose a snapshot (256 is current system): " subvol 


         echo -e "\nPlease enter extra mount options (ex., ro ):"
         read options 
         [ ! "$options" = "" ] && options=","$options

         echo -e "\nWill proceed with the following mount:\n\nmount -o subvolid=$subvol$options ${root} /\n"
         sleep 4

         umount $root_dir
         mount --mkdir -o subvolid=$subvol$options ${root} $root_dir

         if [ "$?" -ne 0 ]; then
            echo "Couldn't mount that choice. Chosing default (256)."
            sleep 2
            mount --mkdir -o subvolid=256 ${root} $root_dir 
         fi

      elif [[ "$key" = "o" ]]; then

         ROOT_MNT="/new_root"
         DIRS="/run/archroot"
         LOWER="${DIRS}/root_ro"
         COWSPACE="${DIRS}/cowspace"
         UPPER="${COWSPACE}/upper"
         WORK="${COWSPACE}/work"

         mkdir -p ${LOWER}
         mount --move ${ROOT_MNT} ${LOWER}

         mkdir -p ${COWSPACE}
         mount -t tmpfs cowspace ${COWSPACE}

         mkdir -p ${UPPER} ${WORK}

         mount -t overlay -o lowerdir=${LOWER},upperdir=${UPPER},workdir=${WORK} rootfs ${ROOT_MNT}

      elif [[ "$key" = "p" ]]; then
 
         local root_mnt="/new_root"
         local lower_dir=$(mktemp -d -p /)
         local ram_dir=$(mktemp -d -p /)
         mount --move ${root_mnt} ${lower_dir}
         mount -t tmpfs cowspace ${ram_dir}
         mkdir -p ${ram_dir}/upper ${ram_dir}/work
         mount -t overlay -o lowerdir=${lower_dir},upperdir=${ram_dir}/upper,workdir=${ram_dir}/work rootfs ${root_mnt}

      elif [[ "$key" = "e" ]] || [[ "$key" = "n" ]] || [[ "$key" = "c" ]]; then

         poll_device ${root} 2
         mkdir /real_root/
         mount ${root} /real_root/
         mount -t tmpfs -o size=80% none /new_root/
      
         if [[ "$key" = "e" ]] || [[ "$key" = "n" ]]; then

            [[ ! -f "/real_root/@/rootfs.tar.gz" ]] || [[ "$key" = "n" ]] && create_archive

            echo "Extracting archive to RAM. Please be patient..."
            tar -xzf /real_root/@/rootfs.tar.gz -C /new_root/

         elif [[ "$key" = "c" ]]; then

            echo "Copying root filesystem to RAM. Please be patient..."

            #cp -p -a -R /real_root/@/* /new_root/
            rsync -a --exclude=rootfs.tar.gz --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ --exclude=/tmp/ --exclude=/run/ --exclude=/mnt/ --exclude=/.snapshots/* --exclude=/var/tmp/ --exclude=/var/cache/ --exclude=/var/log/ --exclude=/mnt/ /real_root/@/ /new_root/

         fi

         touch /new_root/LIVE
         umount /real_root/

         LIVE_mount() {
            echo "Live system on RAM."
         }
         
         mount_handler=LIVE_mount

      elif [[ "$key" = "d" ]]; then

         echo "Entering emergency shell."

         bash

      elif [[ "$key" = "b" ]]; then

         echo "Continuing boot..."

      fi

   fi
}
